export type AnalyticsEvent =
  // Existing in-app events
  | 'menu_generated'
  | 'meal_viewed'
  | 'meal_consumed'
  | 'meal_rated'
  | 'meal_swapped'
  | 'meal_saved_favorite'
  | 'shopping_item_checked'
  | 'shopping_day_filter_used'
  | 'water_logged'
  | 'weight_logged'
  | 'streak_completed'
  | 'streak_badge_earned'
  | 'push_permission_granted'
  | 'push_permission_denied'
  | 'servings_changed'
  | 'weekly_summary_viewed'
  // Funnel events
  | 'onboarding_started'
  | 'onboarding_completed'
  | 'payment_email_entered'
  | 'payment_consents_checked'
  | 'plan_selected'
  | 'checkout_started'
  | 'checkout_blocked'
  | 'redirected_to_liqpay'
  | 'payment_succeeded'
  | 'payment_failed'
  | 'login_completed';
